production:
  lesson_reminder_sweep:
    class: ReminderSweepJob
    schedule: "* * * * *"
  late_lesson_reminder_sweep:
    class: LateReminderSweepJob
    schedule: "* * * * *"
  recurring_lesson_generation:
    class: RecurringLessonGenerationJob
    schedule: "10 0 * * * UTC"
